# Generated by Django 3.0.4 on 2020-03-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillchillapi', '0008_auto_20200318_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
